# Autogenerated config.py
# Documentation:
#   qute://help/configuring.html
#   qute://help/settings.html

# Uncomment this to still load settings configured via autoconfig.yml
# config.load_autoconfig()

# Top border color of the completion widget category headers.
# Type: QssColor
c.colors.completion.category.border.top = 'black'

# Background color of the tab bar.
# Type: QtColor
c.colors.tabs.bar.bg = '#999999'

# Background color of unselected even tabs.
c.colors.tabs.even.bg = '#333333'

# Background color of unselected odd tabs.
# Type: QtColor
c.colors.tabs.odd.bg = '#333333'

# Background color of selected odd tabs.
# Type: QtColor
c.colors.tabs.selected.odd.bg = '#999999'

# Background color of selected even tabs
c.colors.tabs.selected.even.bg = '#999999'

# Foreground color of selected even tabs
c.colors.tabs.selected.even.fg = '#333333'

# Foreground color of selected odd tabs
c.colors.tabs.selected.odd.fg = '#333333'

# Position of the status bar.
# Type: VerticalPosition
# Valid values:
#   - top
#   - bottom
c.statusbar.position = 'bottom'

# Scaling factor for favicons in the tab bar. The tab size is unchanged,
# so big favicons also require extra `tabs.padding`.
# Type: Float
c.tabs.favicons.scale = 1.0

# Page to open if :open -t/-b/-w is used without URL. Use `about:blank`
# for a blank page.
# Type: FuzzyUrl
c.url.default_page = 'https://kalen.pw'

# Page(s) to open at the start.
# Type: List of FuzzyUrl, or FuzzyUrl
c.url.start_pages = 'https://kalen.pw'
